---
- name: Using Ansible to send an HTTP GET request
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Send HTTP GET to requestbin.com
    ansible.builtin.uri:
      url: "{{ urltolookup }}"
      method: GET
    register: results

  - name: Display results
    ansible.builtin.debug:
      var: results