---
- name: complex variable data
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ~/mycode/vars/storagevars.yml

  tasks:
  - name: debug with_dict
    ansible.builtin.debug:
      var: item
    loop: "{{ compute_work|dict2items }}"
      