- name: Use Redfish to gather CPU Inventory, and Virtual Media Information
  hosts: Redfish
  connection: local
  gather_facts: false

  collections:
    community.general

  tasks:
  - name: Get CPU Inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: results
  
  - name: Print fetched information
    ansible.builtin.debug:
      msg: "{{ results.redfish_facts }}"