---
- name: A playbook to preform a graceful reboot of a server
  hosts: redfish_apis    # group name
  connection: local      # we need to run HTTP(s) to talk to the RedFish APIs
  gather_facts: false

  # collections:
  # - community.general      # to update / install, "ansible-galaxy collection install community.general"

  tasks:

         - name: Graceful restart of server
           community.general.redfish_command:
               category: Systems
               command: PowerReboot
               baseuri: "{{ baseuri }}"
               username: "{{ username }}"
               password: "{{ password }}"
