---
- name: Using Ansible to send an HTTP Delete request
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Send HTTP DELETE to requestbin.com
    ansible.builtin.uri:
      url: "{{ urltolookup }}"
      method: DELETE
      headers:
        Content-Type: application/json
        Storage-auth-token: abcdefg717
      body_format: json
      body:
        name: student
        policy: bronze
        storage_type: flash